//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicine.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urunler()
        {
            this.Tbl_SiparisDetay = new HashSet<Tbl_SiparisDetay>();
        }
    
        public int ID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> STOK { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public string RESIM { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string BARKOD { get; set; }
    
        public virtual Tbl_Kategoriler Tbl_Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SiparisDetay> Tbl_SiparisDetay { get; set; }
    }
}
